# 인공신경망 XOR 구현

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
x = torch.FloatTensor([[0,0],[0,1],[1,0],[1,1]])
y = torch.FloatTensor([[0],[1],[1],[0]])

In [3]:
model = nn.Sequential(
    nn.Linear(2, 10, bias=True),
    nn.Sigmoid(),
    nn.Linear(10,10, bias=True),
    nn.Sigmoid(),
    nn.Linear(10,10, bias=True),
    nn.Sigmoid(),
    nn.Linear(10,1, bias=True),
    nn.Sigmoid()
)

In [4]:
criterion = torch.nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=1)

In [5]:
for epoch in range(10001):
    optimizer.zero_grad()

    y_hat = model(x)
    cost = criterion(y_hat, y)
    cost.backward()
    optimizer.step()

    if epoch % 1000 == 0:
        print('Epoch:', epoch, 'Cost:',cost.item())


Epoch: 0 Cost: 0.7017521262168884
Epoch: 1000 Cost: 0.6931344270706177
Epoch: 2000 Cost: 0.6931136846542358
Epoch: 3000 Cost: 0.6930578351020813
Epoch: 4000 Cost: 0.6927046775817871
Epoch: 5000 Cost: 0.006952058058232069
Epoch: 6000 Cost: 0.0006626611575484276
Epoch: 7000 Cost: 0.0003269371809437871
Epoch: 8000 Cost: 0.0002136591647285968
Epoch: 9000 Cost: 0.00015761263784952462
Epoch: 10000 Cost: 0.00012434643576852977


In [6]:
with torch.no_grad():
    h = model(x)
    prediction = (h>0.5).float()
    accuray = (prediction==y).float().mean()
    print(h)
    print(prediction)
    print(accuray)
    print(y)
    

tensor([[1.0578e-04],
        [9.9987e-01],
        [9.9988e-01],
        [1.4393e-04]])
tensor([[0.],
        [1.],
        [1.],
        [0.]])
tensor(1.)
tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [7]:
import matplotlib.pyplot as plt
import numpy as np

In [8]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

x = np.arange(-5.0, 5.0, 0.1)
y = sigmoid(x)


In [9]:
# plt.plot(x,y)
# plt.plot([0.0,0.0], [1.0, 0.0], ':')
# plt.title('Sigmoid Function')

In [10]:
# x = np.arange(-5.0, 5.0, 0.1)
# y = np.tanh(x)
# plt.plot(x,y)
# plt.plot([0,0], [1.0,0.0], ':')
# plt.title('Sigmoid Function')
# plt.show()

In [11]:
x = np.arange(-5.0, 5.0, 0.1)
y = np.exp(x) / np.sum(np.exp(x))
print(y.sum())
print(y)

0.9999999999999998
[4.77496908e-06 5.27715696e-06 5.83216040e-06 6.44553406e-06
 7.12341680e-06 7.87259308e-06 8.70056093e-06 9.61560691e-06
 1.06268891e-05 1.17445288e-05 1.29797117e-05 1.43447999e-05
 1.58534556e-05 1.75207781e-05 1.93634544e-05 2.13999267e-05
 2.36505767e-05 2.61379295e-05 2.88868796e-05 3.19249392e-05
 3.52825144e-05 3.89932088e-05 4.30941604e-05 4.76264128e-05
 5.26353263e-05 5.81710319e-05 6.42889328e-05 7.10502589e-05
 7.85226798e-05 8.67809821e-05 9.59078177e-05 1.05994531e-04
 1.17142073e-04 1.29462012e-04 1.43077651e-04 1.58125259e-04
 1.74755438e-04 1.93134628e-04 2.13446774e-04 2.35895167e-04
 2.60704478e-04 2.88123007e-04 3.18425169e-04 3.51914236e-04
 3.88925379e-04 4.29829018e-04 4.75034531e-04 5.24994349e-04
 5.80208486e-04 6.41229545e-04 7.08668245e-04 7.83199535e-04
 8.65569349e-04 9.56602073e-04 1.05720879e-03 1.16839641e-03
 1.29127773e-03 1.42708260e-03 1.57717018e-03 1.74304262e-03
 1.92636001e-03 2.12895706e-03 2.35286143e-03 2.60031403e-03
 2.87