In [152]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [76]:
torch.manual_seed(1)
x_data = torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data = torch.FloatTensor([[3],[5],[7],[9],[11]])

In [77]:
model = nn.Linear(1,1) # 입력 크기, 출력 크기 -> input_dim = 1, output_dim = 1
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [78]:
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [79]:
nb_epochs = 20000

for epoch in range(nb_epochs):
    prediction = model(x_data)
    cost = F.mse_loss(prediction, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch:', epoch, 'Cost:', cost.item())

Epoch: 0 Cost: 39.16685104370117
Epoch: 100 Cost: 0.08463062345981598
Epoch: 200 Cost: 0.04298952594399452
Epoch: 300 Cost: 0.021837208420038223
Epoch: 400 Cost: 0.01109258271753788
Epoch: 500 Cost: 0.00563468411564827
Epoch: 600 Cost: 0.0028622171375900507
Epoch: 700 Cost: 0.0014539161929860711
Epoch: 800 Cost: 0.0007385412463918328
Epoch: 900 Cost: 0.00037515218718908727
Epoch: 1000 Cost: 0.00019056595920119435
Epoch: 1100 Cost: 9.680409129941836e-05
Epoch: 1200 Cost: 4.91717473778408e-05
Epoch: 1300 Cost: 2.497919740562793e-05
Epoch: 1400 Cost: 1.2689983122982085e-05
Epoch: 1500 Cost: 6.447205578297144e-06
Epoch: 1600 Cost: 3.276181814726442e-06
Epoch: 1700 Cost: 1.6654261116855196e-06
Epoch: 1800 Cost: 8.460160643153358e-07
Epoch: 1900 Cost: 4.302897309571563e-07
Epoch: 2000 Cost: 2.1860606125301274e-07
Epoch: 2100 Cost: 1.1113379372318377e-07
Epoch: 2200 Cost: 5.657594925878584e-08
Epoch: 2300 Cost: 2.86554158179797e-08
Epoch: 2400 Cost: 1.4702209227834828e-08
Epoch: 2500 Cost: 7.

In [80]:
new_data = torch.FloatTensor([10])
y_pred = model(new_data)
print(y_pred)
print(list(model.parameters()))

tensor([21.0000], grad_fn=<AddBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [81]:
x_tain = torch.FloatTensor([[73., 80., 75.],
                            [93., 88., 93.],
                            [89., 91., 90.],
                            [96., 98., 100.],
                            [73., 66., 70.]])
t_train = torch.FloatTensor([[152.],
                            [185.],
                            [180.],
                            [196.],
                            [142.]])

In [82]:
model = nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [83]:
optimizer = optim.SGD(model.parameters(), lr=1e-6)

In [99]:
for epoch in range(nb_epochs):
    prediction = model(x_tain)
    cost = F.mse_loss(prediction, t_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0 :
        print('Epoch:', epoch, 'Cost:', cost.item())

Epoch: 0 Cost: 0.16346625983715057
Epoch: 400 Cost: 0.1634562909603119
Epoch: 800 Cost: 0.16344048082828522
Epoch: 1200 Cost: 0.16342493891716003
Epoch: 1600 Cost: 0.16340823471546173
Epoch: 2000 Cost: 0.16339616477489471
Epoch: 2400 Cost: 0.16338039934635162
Epoch: 2800 Cost: 0.16337010264396667
Epoch: 3200 Cost: 0.1633537858724594
Epoch: 3600 Cost: 0.1633395403623581
Epoch: 4000 Cost: 0.16332539916038513
Epoch: 4400 Cost: 0.16331364214420319
Epoch: 4800 Cost: 0.1633032113313675
Epoch: 5200 Cost: 0.16328655183315277
Epoch: 5600 Cost: 0.16327118873596191
Epoch: 6000 Cost: 0.1632615625858307
Epoch: 6400 Cost: 0.16324792802333832
Epoch: 6800 Cost: 0.16323406994342804
Epoch: 7200 Cost: 0.16321973502635956
Epoch: 7600 Cost: 0.16320838034152985
Epoch: 8000 Cost: 0.16319569945335388
Epoch: 8400 Cost: 0.16317962110042572
Epoch: 8800 Cost: 0.1631644070148468
Epoch: 9200 Cost: 0.1631498634815216
Epoch: 9600 Cost: 0.16314232349395752
Epoch: 10000 Cost: 0.16312938928604126
Epoch: 10400 Cost: 0.16

In [106]:
new_train = torch.FloatTensor([[75,80,75]])
y_pred = model(new_train)
print(y_pred)
print(list(model.parameters()))

tensor([[153.7640]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[1.0707, 0.5359, 0.4031]], requires_grad=True), Parameter containing:
tensor([0.3584], requires_grad=True)]


# class 사용 single regression

In [118]:
torch.manual_seed(1)
x_data = torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data = torch.FloatTensor([[3],[5],[7],[9],[11]])

In [119]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)
    
    

In [120]:
model = LinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 20000
for epoch in range(nb_epochs):
    prediction = model(x_data)
    cost = F.mse_loss(prediction, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print('Epoch:', epoch, 'Cost:', cost.item())

Epoch: 0 Cost: 39.16685104370117
Epoch: 400 Cost: 0.01109258271753788
Epoch: 800 Cost: 0.0007385412463918328
Epoch: 1200 Cost: 4.91717473778408e-05
Epoch: 1600 Cost: 3.276181814726442e-06
Epoch: 2000 Cost: 2.1860606125301274e-07
Epoch: 2400 Cost: 1.4702209227834828e-08
Epoch: 2800 Cost: 9.986707016906848e-10
Epoch: 3200 Cost: 1.0809344391793374e-10
Epoch: 3600 Cost: 5.426272625674855e-11
Epoch: 4000 Cost: 5.426272625674855e-11
Epoch: 4400 Cost: 5.426272625674855e-11
Epoch: 4800 Cost: 5.426272625674855e-11
Epoch: 5200 Cost: 5.426272625674855e-11
Epoch: 5600 Cost: 5.426272625674855e-11
Epoch: 6000 Cost: 5.426272625674855e-11
Epoch: 6400 Cost: 5.426272625674855e-11
Epoch: 6800 Cost: 5.426272625674855e-11
Epoch: 7200 Cost: 5.426272625674855e-11
Epoch: 7600 Cost: 5.426272625674855e-11
Epoch: 8000 Cost: 5.426272625674855e-11
Epoch: 8400 Cost: 5.426272625674855e-11
Epoch: 8800 Cost: 5.426272625674855e-11
Epoch: 9200 Cost: 5.426272625674855e-11
Epoch: 9600 Cost: 5.426272625674855e-11
Epoch: 10

In [131]:
new_data = torch.FloatTensor([[1.5]])
print(model(new_data))

tensor([[4.0000]], grad_fn=<AddmmBackward0>)


In [137]:
x_train = torch.FloatTensor([[73., 80., 75.],
                            [93., 88., 93.],
                            [89., 91., 90.],
                            [96., 98., 100.],
                            [73., 66., 70.]])
t_train = torch.FloatTensor([[152.],
                            [185.],
                            [180.],
                            [196.],
                            [142.]])

In [138]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)
    
    

In [139]:
model = MultiLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-6)

In [ ]:
# nb_epochs = 20000
for epoch in range(nb_epochs):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, t_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print('Epoch:', epoch, 'Cost:', cost.item())

In [154]:
new_data = torch.FloatTensor([[73., 80., 75.]])
pred_y = model(new_data)
print(pred_y)

tensor([[151.2944]], grad_fn=<AddmmBackward0>)


In [197]:
data = np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype='float32')
x_data = data[:, 0:-1]
t_data = data[:, [-1]]
print(x_data[:5])
print(t_data[:5])
x_train = torch.from_numpy(x_data)
y_train = torch.from_numpy(t_data)
print(x_tain[:5])
print(y_train[:5])

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]
tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [198]:
torch.manual_seed(1)

model = nn.Linear(3,1)
optimizer = optim.SGD(model.parameters(), lr=1e-6)

In [199]:
nb_epochs = 100000
for epoch in range(nb_epochs):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 4000 == 0:
        print('Epoch:', epoch, 'Cost:', cost.item())

Epoch: 0 Cost: 28693.490234375
Epoch: 4000 Cost: 13.772063255310059
Epoch: 8000 Cost: 12.176605224609375
Epoch: 12000 Cost: 10.934386253356934
Epoch: 16000 Cost: 9.962173461914062
Epoch: 20000 Cost: 9.197564125061035
Epoch: 24000 Cost: 8.593523979187012
Epoch: 28000 Cost: 8.114365577697754
Epoch: 32000 Cost: 7.732822418212891
Epoch: 36000 Cost: 7.42799186706543
Epoch: 40000 Cost: 7.183600425720215
Epoch: 44000 Cost: 6.987161159515381
Epoch: 48000 Cost: 6.828953266143799
Epoch: 52000 Cost: 6.701241970062256
Epoch: 56000 Cost: 6.597883701324463
Epoch: 60000 Cost: 6.514108657836914
Epoch: 64000 Cost: 6.446160316467285
Epoch: 68000 Cost: 6.390915393829346
Epoch: 72000 Cost: 6.3459367752075195
Epoch: 76000 Cost: 6.309393405914307
Epoch: 80000 Cost: 6.279495716094971
Epoch: 84000 Cost: 6.255125045776367
Epoch: 88000 Cost: 6.23521614074707
Epoch: 92000 Cost: 6.218939781188965
Epoch: 96000 Cost: 6.205629348754883


In [213]:
new_data = torch.FloatTensor([[73,80,75]])
pred = model(new_data)
print(pred)

tensor([[152.8082]], grad_fn=<AddmmBackward0>)


In [210]:
class MultiLinearRegressModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)
    

In [211]:
model = MultiLinearRegressModel()
optimizer = optim.SGD(model.parameters(), lr=1e-6)

In [212]:
for epoch in range(nb_epochs):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 4000 ==0:
        print('Epoch:', epoch, 'Cost:', cost)

Epoch: 0 Cost: tensor(28388., grad_fn=<MseLossBackward0>)
Epoch: 400 Cost: tensor(13.2477, grad_fn=<MseLossBackward0>)
Epoch: 800 Cost: tensor(13.0749, grad_fn=<MseLossBackward0>)
Epoch: 1200 Cost: tensor(12.9066, grad_fn=<MseLossBackward0>)
Epoch: 1600 Cost: tensor(12.7427, grad_fn=<MseLossBackward0>)
Epoch: 2000 Cost: tensor(12.5831, grad_fn=<MseLossBackward0>)
Epoch: 2400 Cost: tensor(12.4276, grad_fn=<MseLossBackward0>)
Epoch: 2800 Cost: tensor(12.2761, grad_fn=<MseLossBackward0>)
Epoch: 3200 Cost: tensor(12.1286, grad_fn=<MseLossBackward0>)
Epoch: 3600 Cost: tensor(11.9848, grad_fn=<MseLossBackward0>)
Epoch: 4000 Cost: tensor(11.8447, grad_fn=<MseLossBackward0>)
Epoch: 4400 Cost: tensor(11.7083, grad_fn=<MseLossBackward0>)
Epoch: 4800 Cost: tensor(11.5753, grad_fn=<MseLossBackward0>)
Epoch: 5200 Cost: tensor(11.4457, grad_fn=<MseLossBackward0>)
Epoch: 5600 Cost: tensor(11.3194, grad_fn=<MseLossBackward0>)
Epoch: 6000 Cost: tensor(11.1963, grad_fn=<MseLossBackward0>)
Epoch: 6400 Co