In [2]:
import numpy as np

In [12]:
a={1,2,3,4,5}
b=np.array(a)
print(a, type(a))
print(b, type(b))

{1, 2, 3, 4, 5} <class 'set'>
{1, 2, 3, 4, 5} <class 'numpy.ndarray'>


In [29]:
aa=[1,2,3,4]
bb=[7,8,9,10]
arr1 = np.array(aa)
arr2 = np.array(bb)
# print(aa+bb)
print(arr1+3)
print(arr1-1)
print(arr1*2)
print(arr1/2)
print(arr1//2)

[4 5 6 7]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]


In [32]:
a1=[[1,1,1],[2,2,2],[3,3,3]]
a2=[1,2,3]
b1=np.array(a1)
b2=np.array(a2)
print(b2)
print(b1)
print(b1 + b2)

[1 2 3]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [59]:
a=[5,4,3,2,5,1,7,6,9]
arr1=np.array(a).reshape(3,3)
print(np.sort(arr1))
print(np.sort(arr1, axis=1))
print(np.sort(arr1, axis=0))
print(np.sort(arr1, axis=0)[::,::-1])

[[3 4 5]
 [1 2 5]
 [6 7 9]]
[[3 4 5]
 [1 2 5]
 [6 7 9]]
[[2 4 1]
 [5 5 3]
 [7 6 9]]
[[1 4 2]
 [3 5 5]
 [9 6 7]]


In [62]:
print(arr1)
print(arr1.transpose())

[[5 4 3]
 [2 5 1]
 [7 6 9]]
[[5 2 7]
 [4 5 6]
 [3 1 9]]


In [72]:
print(arr1.transpose()>=5)
print(np.all(arr1<3))
print(np.any(arr1<3))

[[ True False  True]
 [False  True  True]
 [False False  True]]
False
True


In [77]:
a1 = np.ones(10)
a2 = np.zeros([3,3])
print(a1)
print(a2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [83]:
b1=np.ones_like(arr1)
b2=np.zeros_like(arr1)
print(b1)
print(b2)


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
