In [50]:
import numpy as np

In [11]:
data=np.genfromtxt("data/ratings.dat", delimiter="::", dtype=np.int64)

In [39]:
print(data[:10,:])
print(data.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]]
(1000209, 4)


In [47]:
movie_ids = np.unique(data[:,1])
print(movie_ids[:10])
print(movie_ids.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(3706,)


In [35]:
meanValue = []
for movie_id in movie_ids:
    data_for_movie = data[data[:,1]==movie_id,:]
    value = data_for_movie[:, 2].mean()
    meanValue.append([movie_id, value])

In [37]:
mean_array = np.array(meanValue, dtype=np.float32)
print(mean_array[:10])
print(mean_array.shape)

[[ 1.         4.1468463]
 [ 2.         3.201141 ]
 [ 3.         3.0167365]
 [ 4.         2.7294118]
 [ 5.         3.0067568]
 [ 6.         3.8787234]
 [ 7.         3.4104803]
 [ 8.         3.014706 ]
 [ 9.         2.6568627]
 [10.         3.5405405]]
(3706, 2)


In [38]:
np.savetxt("data/movieId_result.csv", mean_array, fmt="%.2f", delimiter=",")