In [1]:
import numpy as np

x_data1 = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
t_data1 = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

x_data=np.array(x_data1)
t_data=np.array(t_data1)
print(x_data)
print(t_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [2]:
w=np.random.rand(3,1)
b=np.random.rand(1)
print(w,b)

[[0.47852577]
 [0.15858855]
 [0.68676724]] [0.42488192]
