In [1]:
import torch
import torch.nn.functional as F


In [3]:
z = torch.FloatTensor([1,2,3])
y_hat=F.softmax(z, dim=0)
print(y_hat)
print(y_hat.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [8]:
z = torch.rand(3,5, requires_grad=True)
y_hat = F.softmax(z, dim=1)
print(y_hat)
print(y_hat.sum(dim=1))

tensor([[0.1348, 0.2964, 0.2279, 0.1248, 0.2161],
        [0.1736, 0.2437, 0.1983, 0.1461, 0.2383],
        [0.1966, 0.1310, 0.2301, 0.2732, 0.1692]], grad_fn=<SoftmaxBackward0>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)


In [23]:
y = torch.randint(5, (3,)).long()
print(y)
y_one_hot = torch.zeros_like(y_hat)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)
print(y_one_hot)

tensor([1, 2, 1])
tensor([[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])


In [25]:
print(y.unsqueeze(1))

tensor([[1],
        [2],
        [1]])


In [26]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [27]:
torch.manual_seed(1)

In [33]:
x_data = [[1,2,1,1],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7]]
y_data = [2,2,2,1,1,1,0,0]
x_train = torch.FloatTensor(x_data)
y_train = torch.LongTensor(y_data)
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [34]:
y_one_hot = torch.zeros(8,3)
y_one_hot.scatter_(1,y_train.unsqueeze(1),1)
print(y_one_hot)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [35]:
W = torch.zeros((4,3),requires_grad=True)
b = torch.zeros((1,3),requires_grad=True)
optimize = optim.SGD([W,b], lr=0.1)

In [37]:
n_epochs = 10000
for epoch in range(n_epochs):
    y_hat = F.softmax(x_train.matmul(W) + b, dim=1)
    cost = (y_one_hot * -torch.log(y_hat)).sum(dim=1).mean()

    optimize.zero_grad()
    cost.backward()
    optimize.step()

    if epoch % 100 == 0:
        print('Epoch:', epoch, 'Cost:', cost.item())

Epoch: 0 Cost: tensor(1.0986, grad_fn=<MeanBackward0>)
Epoch: 100 Cost: tensor(0.7042, grad_fn=<MeanBackward0>)
Epoch: 200 Cost: tensor(0.6230, grad_fn=<MeanBackward0>)
Epoch: 300 Cost: tensor(0.5657, grad_fn=<MeanBackward0>)
Epoch: 400 Cost: tensor(0.5153, grad_fn=<MeanBackward0>)
Epoch: 500 Cost: tensor(0.4677, grad_fn=<MeanBackward0>)
Epoch: 600 Cost: tensor(0.4213, grad_fn=<MeanBackward0>)
Epoch: 700 Cost: tensor(0.3754, grad_fn=<MeanBackward0>)
Epoch: 800 Cost: tensor(0.3298, grad_fn=<MeanBackward0>)
Epoch: 900 Cost: tensor(0.2851, grad_fn=<MeanBackward0>)
Epoch: 1000 Cost: tensor(0.2482, grad_fn=<MeanBackward0>)
Epoch: 1100 Cost: tensor(0.2327, grad_fn=<MeanBackward0>)
Epoch: 1200 Cost: tensor(0.2214, grad_fn=<MeanBackward0>)
Epoch: 1300 Cost: tensor(0.2111, grad_fn=<MeanBackward0>)
Epoch: 1400 Cost: tensor(0.2017, grad_fn=<MeanBackward0>)
Epoch: 1500 Cost: tensor(0.1931, grad_fn=<MeanBackward0>)
Epoch: 1600 Cost: tensor(0.1852, grad_fn=<MeanBackward0>)
Epoch: 1700 Cost: tensor(0

In [38]:
model = nn.Linear(4,3)
optimizer = optim.SGD(model.parameters(), lr=0.1)
n_epochs = 10000

In [40]:
for epoch in range(n_epochs):
    y_hat = model(x_train)
    cost = F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 ==0:
        print('Epoch:', epoch, 'Cost:', cost.item())

Epoch: 0 Cost: tensor(1.6168, grad_fn=<NllLossBackward0>)
Epoch: 100 Cost: tensor(0.6589, grad_fn=<NllLossBackward0>)
Epoch: 200 Cost: tensor(0.5734, grad_fn=<NllLossBackward0>)
Epoch: 300 Cost: tensor(0.5182, grad_fn=<NllLossBackward0>)
Epoch: 400 Cost: tensor(0.4733, grad_fn=<NllLossBackward0>)
Epoch: 500 Cost: tensor(0.4335, grad_fn=<NllLossBackward0>)
Epoch: 600 Cost: tensor(0.3966, grad_fn=<NllLossBackward0>)
Epoch: 700 Cost: tensor(0.3609, grad_fn=<NllLossBackward0>)
Epoch: 800 Cost: tensor(0.3254, grad_fn=<NllLossBackward0>)
Epoch: 900 Cost: tensor(0.2892, grad_fn=<NllLossBackward0>)
Epoch: 1000 Cost: tensor(0.2541, grad_fn=<NllLossBackward0>)
Epoch: 1100 Cost: tensor(0.2350, grad_fn=<NllLossBackward0>)
Epoch: 1200 Cost: tensor(0.2235, grad_fn=<NllLossBackward0>)
Epoch: 1300 Cost: tensor(0.2131, grad_fn=<NllLossBackward0>)
Epoch: 1400 Cost: tensor(0.2035, grad_fn=<NllLossBackward0>)
Epoch: 1500 Cost: tensor(0.1948, grad_fn=<NllLossBackward0>)
Epoch: 1600 Cost: tensor(0.1867, gra

In [42]:
prodiction = model(x_train)
print(prodiction)

tensor([[-11.4186,  -0.1089,  11.8237],
        [ -4.3004,   0.4548,   4.3716],
        [-18.3864,   8.3331,  11.4630],
        [-12.6069,   8.7536,   5.5109],
        [  0.9640,   3.5058,  -2.2738],
        [  4.2153,   7.4299,  -9.0252],
        [  7.0719,   4.7319,  -9.1731],
        [ 10.5022,   5.6714, -13.0725]], grad_fn=<AddmmBackward0>)


In [43]:
class SoftmaxClassModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4,3)

    def forward(self, x):
        return self.linear(x)

In [44]:
model = SoftmaxClassModel()
optimizer = optim.SGD(model.parameters(), lr=0.1)
n_epochs = 10000

In [45]:
for epoch in range(n_epochs):
    y_hat = model(x_train)
    cost = F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch:', epoch, 'Cost:', cost)

Epoch: 0 Cost: tensor(2.6376, grad_fn=<NllLossBackward0>)
Epoch: 100 Cost: tensor(0.6479, grad_fn=<NllLossBackward0>)
Epoch: 200 Cost: tensor(0.5646, grad_fn=<NllLossBackward0>)
Epoch: 300 Cost: tensor(0.5110, grad_fn=<NllLossBackward0>)
Epoch: 400 Cost: tensor(0.4672, grad_fn=<NllLossBackward0>)
Epoch: 500 Cost: tensor(0.4283, grad_fn=<NllLossBackward0>)
Epoch: 600 Cost: tensor(0.3919, grad_fn=<NllLossBackward0>)
Epoch: 700 Cost: tensor(0.3567, grad_fn=<NllLossBackward0>)
Epoch: 800 Cost: tensor(0.3216, grad_fn=<NllLossBackward0>)
Epoch: 900 Cost: tensor(0.2856, grad_fn=<NllLossBackward0>)
Epoch: 1000 Cost: tensor(0.2508, grad_fn=<NllLossBackward0>)
Epoch: 1100 Cost: tensor(0.2321, grad_fn=<NllLossBackward0>)
Epoch: 1200 Cost: tensor(0.2209, grad_fn=<NllLossBackward0>)
Epoch: 1300 Cost: tensor(0.2106, grad_fn=<NllLossBackward0>)
Epoch: 1400 Cost: tensor(0.2013, grad_fn=<NllLossBackward0>)
Epoch: 1500 Cost: tensor(0.1927, grad_fn=<NllLossBackward0>)
Epoch: 1600 Cost: tensor(0.1848, gra

In [47]:
prediction = model(x_train)
print(prediction)

tensor([[-11.5036,  -0.2332,  11.5479],
        [ -4.5121,   0.3314,   4.2517],
        [-18.6580,   8.3967,  11.5297],
        [-13.0537,   8.7771,   5.5309],
        [  0.2068,   2.7514,  -3.0321],
        [  3.6674,   6.8846,  -8.6047],
        [  6.2557,   3.9119,  -9.5963],
        [  9.5301,   4.7040, -13.5656]], grad_fn=<AddmmBackward0>)
