In [1]:
import numpy as np

In [10]:
def myfunc1(x):
    return x**2

def myfunc2(x):
    # 3x**2 + 2*x+1 = 6x + 2
    return 3*x**2 + 2*x+1 

def numerical_derivative(f,x):
    # 1*1/10000
    delta_x = 1e-4 

    return (f(x + delta_x) - f(x-delta_x)) / (2*delta_x)

result = numerical_derivative(myfunc1, 3)
print(result)

6.000000000012662


In [18]:
result2 = numerical_derivative(myfunc2, 2)
print(result2)

14.000000000020663


In [21]:
# 2x + 3xy + y**3 : x로 미분 : 2 + 3y, y에 대한 미분 : 3x + 3y**2
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("x = ", x)
    print("grad = ", grad)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index
        print("dix: ", idx, "x[dix]", x[idx])
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)

        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2)/(2*delta_x)
        print('grad[idx] : ', grad[idx])
        print('grad : ', grad)
        x[idx] = tmp_val
        it.iternext()

    return grad


In [22]:
def func1(input):
    x = input[0]
    y = input[1]
    return (2*x + 3*x*y + np.power(y,3)) # 2x + 3xy + y3승

In [23]:
numerical_derivative(func1, np.array([3.0 ,2.0]))

x =  [3. 2.]
grad =  [0. 0.]
dix:  (0,) x[dix] 3.0
grad[idx] :  7.999999999999119
grad :  [8. 0.]
dix:  (1,) x[dix] 2.0
grad[idx] :  21.000000010040765
grad :  [ 8.         21.00000001]


array([ 8.        , 21.00000001])

In [28]:
numerical_derivative(myfunc1, np.array([3.0]))

x =  [3.]
grad =  [0.]
dix:  (0,) x[dix] 3.0
grad[idx] :  6.000000000012662
grad :  [6.]


array([6.])

In [34]:
def func2(input):
    w = input[0][0]
    x = input[0][1]
    y = input[1][0]
    z = input[1][1]
    return (w*x + x*y*z + 3*w + z*np.power(y,2))

In [35]:
numerical_derivative(func2, np.array([[1.0,2.0],[3.0,4.0]]))

x =  [[1. 2.]
 [3. 4.]]
grad =  [[0. 0.]
 [0. 0.]]
dix:  (0, 0) x[dix] 1.0
grad[idx] :  5.000000000023874
grad :  [[5. 0.]
 [0. 0.]]
dix:  (0, 1) x[dix] 2.0
grad[idx] :  13.00000000000523
grad :  [[ 5. 13.]
 [ 0.  0.]]
dix:  (1, 0) x[dix] 3.0
grad[idx] :  32.00000000006753
grad :  [[ 5. 13.]
 [32.  0.]]
dix:  (1, 1) x[dix] 4.0
grad[idx] :  15.000000000000568
grad :  [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])